app_commende:
    resource: "@AppBundle/Resources/config/routing/commende.yml"
    prefix:   /commende

app_produit:
    resource: "@AppBundle/Resources/config/routing/produit.yml"
    prefix:   /produit

app_point_vente:
    resource: "@AppBundle/Resources/config/routing/pointvente.yml"
    prefix:   /point/vente

app_formated:
    resource: "@AppBundle/Resources/config/routing/formated.yml"
   
kpi:
    path:     /kpi
    defaults: { _controller: "AppBundle:App:kpi" }
    methods:  GET

homepage:
    path:     /
    defaults: { _controller: "AppBundle:App:index" }
    methods:  GET

export_excel:
    path:     /performances
    defaults: { _controller: "AppBundle:App:ventePeriodeExcel" }
    methods:  GET

export_excel_pointages:
    path:     /pointages
    defaults: { _controller: "AppBundle:App:pointagesPeriodeExcel" }
    methods:  GET


set_periode:
    path:     /set/periode
    defaults: { _controller: "AppBundle:App:setPeriode" }
    methods:  POST

